#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

# alfresco
VERSION="5.0.d"
URL="http://sourceforge.net/projects/alfresco/files/Alfresco%20${VERSION}%20Community/alfresco-community-${VERSION}.zip"
dl $URL /usr/local/src

