#!/bin/bash -e
# regenerate alfresco mysql password

. /etc/default/inithooks

CONF=/etc/alfresco/config
PASSWORD=$(mcookie)
sed -i "s|dataSource.password =.*|dataSource.password = \"$PASSWORD\"|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=alfresco --pass="$PASSWORD"

